CREATE TABLE `game_saves` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`coins` int NOT NULL DEFAULT 0,
	`level` int NOT NULL DEFAULT 1,
	`xp` int NOT NULL DEFAULT 0,
	`food` int NOT NULL DEFAULT 100,
	`poop` int NOT NULL DEFAULT 0,
	`hunger` int NOT NULL DEFAULT 100,
	`happy` int NOT NULL DEFAULT 100,
	`sus` int NOT NULL DEFAULT 0,
	`x` int NOT NULL DEFAULT 400,
	`y` int NOT NULL DEFAULT 300,
	`speed` int NOT NULL DEFAULT 5,
	`alive` boolean NOT NULL DEFAULT true,
	`capyColor` varchar(7) NOT NULL DEFAULT '#8B7355',
	`capySize` int NOT NULL DEFAULT 50,
	`totalScore` int NOT NULL DEFAULT 0,
	`totalXP` int NOT NULL DEFAULT 0,
	`foodEaten` int NOT NULL DEFAULT 0,
	`gamesPlayed` int NOT NULL DEFAULT 0,
	`workCount` int NOT NULL DEFAULT 0,
	`affectionCount` int NOT NULL DEFAULT 0,
	`bathroomCount` int NOT NULL DEFAULT 0,
	`colorChanges` int NOT NULL DEFAULT 0,
	`size` int NOT NULL DEFAULT 50,
	`inventory` text NOT NULL DEFAULT ('{}'),
	`lastSaved` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `game_saves_id` PRIMARY KEY(`id`),
	CONSTRAINT `game_saves_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
ALTER TABLE `game_saves` ADD CONSTRAINT `game_saves_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;